# Global options:

[mypy]

# Mypy checks should treat all unannotated function parameters as having type Any.
disallow_untyped_defs = False

# This will make mypy treat unannotated function parameters with a default value as having type Any.
disallow_untyped_calls = False

# This will make mypy treat any untyped function definitions as errors.
check_untyped_defs = True

# This will forbid defining functions without type annotations or with incomplete type annotations.
disallow_incomplete_defs = True

# This will warn about casting an expression to Union type.
warn_redundant_casts = True

# This will disallow usage of the Any type.
disallow_any_generics = False

# This will make mypy warn about inferred types that are Any.
warn_unused_ignores = True

# Do not follow imports (except for ones found in typeshed).
ignore_missing_imports = False

disable_error_code = assignment, call-overload, operator, attr-defined, misc, index, union-attr

# Per-module options:

# This will make mypy ignore errors from missing stubs for these modules.
[mypy-pandas]
ignore_missing_imports = True

[mypy-statsmodels.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-fake_useragent]
ignore_missing_imports = True

[mypy-pymc]
ignore_missing_imports = True

[mypy-nutpie]
ignore_missing_imports = True

[mypy-seaborn]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

