#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# %% Imports

import unittest

import arviz as az
import numpy as np
import pandas as pd

from pfd.helpers.base import create_pm_mod
from pfd.utils import est_pm_mod

# %% Class


class IntegrationTest(unittest.TestCase):
    def test_pass_model_to_sampler(self) -> None:
        """
        Perform integration test.

        Check if the model generated by create_dhs is successfully
        passed and estimated by run_sampler.
        """

        # Create example data
        n_per = 50
        n_obs = 100
        cols = [f"OddsMvt{i}" for i in range(0, n_per)]
        df = pd.DataFrame(data=np.random.rand(n_obs, n_per), columns=cols)
        df["Bookies"] = np.repeat(["Pinnacle", "Marathonbet"], n_per)
        df["Match"] = np.random.choice([0, 1], size=n_obs, p=[0.5, 0.5])

        # Instatiate model
        model = create_pm_mod(df=df, n_per=n_per, incr=5)

        # Estimate model
        trace = est_pm_mod(
            model=model,
            seed=42,
            n_draws=100,
            n_tune=100,
            n_chains=2,
            n_cores=2,
            targ_acpt=0.8,
        )

        self.assertIsInstance(trace, az.InferenceData)


if __name__ == "__main__":
    unittest.main()
