#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# %% Imports

import unittest

import arviz as az
import numpy as np
import pandas as pd

from pfd.utils import estimate_pm_mod
from pfd.helpers import create_pm_mod

# %% Class


class IntegrationTest(unittest.TestCase):
    def test_pass_model_to_sampler(self) -> None:
        """
        Perform integration test.

        Check if the model generated by create_dhs is successfully
        passed and estimated by run_sampler.
        """

        # Create example data
        cols = [f"OddsMvt{i}" for i in range(0, 21)]
        df = pd.DataFrame(data=np.random.rand(100, 21), columns=cols)
        df["Bookies"] = np.repeat(["Pinnacle", "Marathonbet"], 50)

        # Instatiate model
        model = create_pm_mod(
            df=df,
            n_per=21,
            incr=4
        )

        # Estimate model
        trace = estimate_pm_mod(
                model=model,
                seed=42,
                n_draws=200,
                n_tune=200,
                n_chains=2,
                n_cores=2,
                targ_acpt=0.8
            )

        self.assertIsInstance(trace, az.InferenceData)


if __name__ == "__main__":
    unittest.main()
