defaults: # Entries below _self_ override the config in this file
  - sampling: fast_sampling
  - general: alt_seed
  - _self_ 
  - override hydra/job_logging: custom

estimation:
  spec: BmHome # Which odds to use for analysis
  compets: null # Which competitions ["ATP", "WTA"] or null
  bm_quantile: 0.25  # Quantile selecting the bookmakers by the number of obs.
  odds_mvmnts: [2, 20] # Minimum and maximum of odds movements
  ts_dur: [12, 72] # Min and max time series duration in hours
  period: Null  # Subperiod in hours of the time series to keep (e.g., last 12)
  resample_freq: 1min # Frequency (min) to which the series is resampled
  pctl: 2  # Percentile time increments
  incr: 5 # Incremental step for periods for GMM estimation
  max_iter: "cue" # Maximum number of iterations for GMM

files:
  clr_plt: stata_colors.json # Color palette
  chrm_driv: chromedriver.exe  # Chrome driver
  acpt_cookies: I-don-t-care-about-cookies.crx # Accept cookies
  cred: credentials.json  # Credentials
  vals: values.dat  # Values

general:
  seed: 42
  save: True # Save objects boolean
  main_scripts: [
        shape_data.py,
        run_estimation.py,
        run_descriptives.py,
    ]

# paths:  # TODO
#   acc: ${hydra:runtime.cwd}/../../accessories/
#   data_ext: ${hydra:runtime.cwd}/../../data/external/
#   data_intrm: ${hydra:runtime.cwd}/../../data/interim/
#   data_proc: ${hydra:runtime.cwd}/../../data/processed/
#   data_raw: ${hydra:runtime.cwd}/../../data/raw/
#   models: ${hydra:runtime.cwd}/../../models/
#   figures: ${hydra:runtime.cwd}/../../reports/figures/
#   tables: ${hydra:runtime.cwd}/../../reports/tables/
#   vals: ${hydra:runtime.cwd}/../../reports/values/
paths:
  acc: ../../../accessories/
  data_ext: ../../../data/external/
  data_intrm: ../../../data/interim/
  data_proc: ../../../data/processed/
  data_raw: ../../../data/raw/
  models: ../../../models/
  figures: ../../../reports/figures/
  tables: ../../../reports/tables/
  vals: ../../../reports/values/


plotting:
  base_size: 16 # Base size of plotting objects
  leg_mkr_size: 1 # Legend marker size
  line_width: 1 # Line width
  mkr_size: 8 # Marker size
  ax_line_width: 0.8  # Axes line width
  xtick_maj_width: 0.8 # Xticks major width
  ytick_maj_width: 0.8 # Yticks major width
  xtick_maj_size: 3.5 # Xticks major size
  ytick_maj_size: 3.5 # Yticks major size
  font_family: sans-serif # Font family

sampling:
  # Normal means problem, multiple regression problem, and real-data example
  hdi: 0.95 # Highest density interval
  n_chains: 4 # Number of chains
  n_draws: 5000 # Number of draws per chain
  n_tune: 2000 # Number of tuning steps (burn-in) per chain
  n_cores: 4 # Number of cores
  targ_acpt: 0.85 # Acceptance probability
  vi_n_iter: 25000 # Number of iterations for variational inference
  vi_n_draws: 10000 # Number of draws for variational inference

scraping:
  headless: False # Do not show browser window
  crawl_till: "2023-11-28 09:00:00"
  repeat_per: 9 # Period in hours during which matches are crawled
                # before new tournaments are crawled
  sleep: 3 # Hours to sleep between repeats
